############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
pageRef = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
pageRef = "/about"
weight = 2

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
url = "/blog"
pageRef = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"
pageRef = "/contact"

[[main]]
parent = "Pages"
name = "About"
url = "/about"
pageRef = "/about"

[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"
pageRef = "/categories"

# footer menu
[[footer]]
name = "About"
url = "/about"
pageRef = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
pageRef = "/pages/privacy-policy"
weight = 3


